# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import dropme.models


class Migration(migrations.Migration):

    dependencies = [
        ('dropme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='readonly_token',
            field=models.CharField(default=dropme.models.random_token_doc, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='allow_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='allow_public_add_documents',
            field=models.BooleanField(default=False, help_text='Allow anyone with the link to add documents to this clipboards'),
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='allow_public_view',
            field=models.BooleanField(default=True, help_text='Allow anyone with the link to view this clipboard'),
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='listable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='token',
            field=models.CharField(default=dropme.models.random_token_clipboard, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='allow_add_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='allow_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='allow_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='allow_add_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='allow_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='allow_view',
            field=models.BooleanField(default=True),
        ),
    ]
