# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropme', '0002_auto_20160523_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='source_title',
            new_name='source_name',
        ),
        migrations.AddField(
            model_name='document',
            name='storage_filename',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='storage_path',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documenttag',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
